# Generated by Django 5.0.6 on 2024-07-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='google',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='instagram',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='linkedin',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='twitter',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='vimeo',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Facebook',
        ),
        migrations.DeleteModel(
            name='Google',
        ),
        migrations.DeleteModel(
            name='Instagram',
        ),
        migrations.DeleteModel(
            name='Linkedin',
        ),
        migrations.DeleteModel(
            name='Twitter',
        ),
        migrations.DeleteModel(
            name='Vimeo',
        ),
        migrations.DeleteModel(
            name='YouTube',
        ),
    ]
